apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator
  namespace: playground
spec:
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: calculator
        image: playground/calculator:v1.0.3
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
